name: chaturvyuha_foundation
description: A new Flutter project for Chaturveda Foundation.

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/chaturvedal-logo.png
    - assets/image_1.png
    - assets/image_2.png
    - assets/image_3.png
