import 'package:flutter/material.dart';
import '../../../core/constants/app_constants.dart';
import '../../widgets/forms/admin_form_section.dart';
import '../../widgets/forms/image_upload_box.dart';
import 'widgets/program_schedule_section.dart';
import 'widgets/program_registration_section.dart';
class CreateProgramPage extends StatefulWidget{const CreateProgramPage({super.key});@override State<CreateProgramPage> createState()=>_CreateProgramPageState();}
class _CreateProgramPageState extends State<CreateProgramPage>{String category='Education',status='Active';bool registration=true,maxParticipants=true;void save()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Program saved as dummy data.')));
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:AppConstants.pageBackground,appBar:AppBar(title:const Text('Create Program'),leading:IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded))),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1200),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const _Intro(),const SizedBox(height:16),LayoutBuilder(builder:(c,cs)=>_layout(cs.maxWidth>=900)),const SizedBox(height:18),Align(alignment:Alignment.centerRight,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppConstants.primaryRed),onPressed:save,icon:const Icon(Icons.save_outlined),label:const Text('Save Program')))])))));
Widget _layout(bool wide){final details=Column(children:[const AdminFormSection(title:'Program Details',child:Column(children:[AdminTextField(label:'Program Title',hint:'Enter program title'),SizedBox(height:14),AdminTextField(label:'Description',hint:'Describe the program',maxLines:5)])),const SizedBox(height:16),const ProgramScheduleSection(),const SizedBox(height:16),ProgramRegistrationSection(registration:registration,maximum:maxParticipants,onRegistration:(v)=>setState(()=>registration=v),onMaximum:(v)=>setState(()=>maxParticipants=v))]);final side=Column(children:[AdminFormSection(title:'Program Settings',child:Column(children:[AdminDropdown(label:'Category',value:category,items:const['Education','Culture','Yoga','Youth','Spiritual'],onChanged:(v){if(v!=null)setState(()=>category=v);}),const SizedBox(height:14),AdminDropdown(label:'Status',value:status,items:const['Active','Draft','Upcoming'],onChanged:(v){if(v!=null)setState(()=>status=v);})])),const SizedBox(height:16),const AdminFormSection(title:'Program Image',child:ImageUploadBox(height:190,subtitle:'Recommended 1200 × 700 px')),const SizedBox(height:16),const AdminFormSection(title:'Instructor / Resource',child:Column(children:[AdminTextField(label:'Instructor Name',hint:'Enter instructor name'),SizedBox(height:14),AdminTextField(label:'Instructor Biography',hint:'Short biography',maxLines:4)]))]);return wide?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:7,child:details),const SizedBox(width:16),Expanded(flex:3,child:side)]):Column(children:[details,const SizedBox(height:16),side]);}
}
class _Intro extends StatelessWidget{const _Intro();@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Create Program',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Create an educational, cultural or community program.',style:TextStyle(color:AppConstants.textSecondary,fontSize:12))]);}
