import 'package:flutter/material.dart';
import '../../../core/constants/app_constants.dart';
import '../../widgets/forms/admin_form_section.dart';
import '../../widgets/forms/image_upload_box.dart';
import 'widgets/media_upload_zone.dart';
import 'widgets/media_details_section.dart';
import 'widgets/media_library_preview.dart';
class UploadMediaPage extends StatefulWidget{const UploadMediaPage({super.key});@override State<UploadMediaPage> createState()=>_UploadMediaPageState();}
class _UploadMediaPageState extends State<UploadMediaPage>{String folder='General',type='Image';final files=<String>[];void add(){setState(()=>files.add('heritage-photo-${files.length+1}.jpg'));}void upload()=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(files.isEmpty?'Choose a dummy file first.':'${files.length} media file(s) ready for upload.')));
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:AppConstants.pageBackground,appBar:AppBar(title:const Text('Upload Media'),leading:IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded))),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1200),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const _Intro(),const SizedBox(height:16),LayoutBuilder(builder:(c,cs)=>_layout(cs.maxWidth>=900)),const SizedBox(height:18),Align(alignment:Alignment.centerRight,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppConstants.primaryRed),onPressed:upload,icon:const Icon(Icons.cloud_upload_outlined),label:const Text('Upload Media')))])))));
Widget _layout(bool wide){final uploader=Column(children:[MediaUploadZone(fileCount:files.length,onPick:add),if(files.isNotEmpty)...[const SizedBox(height:16),MediaLibraryPreview(files:files)],const SizedBox(height:16),const AdminFormSection(title:'Quick Image Upload',child:ImageUploadBox(height:150,subtitle:'Click to simulate file selection'))]);final side=Column(children:[MediaDetailsSection(folder:folder,type:type,onFolder:(v)=>setState(()=>folder=v??folder),onType:(v)=>setState(()=>type=v??type)),const SizedBox(height:16),const AdminFormSection(title:'File Guidelines',child:_Guidelines())]);return wide?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:7,child:uploader),const SizedBox(width:16),Expanded(flex:3,child:side)]):Column(children:[uploader,const SizedBox(height:16),side]);}
}
class _Intro extends StatelessWidget{const _Intro();@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Upload Media',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Upload and organize images, audio, video and documents.',style:TextStyle(color:AppConstants.textSecondary,fontSize:12))]);}
class _Guidelines extends StatelessWidget{const _Guidelines();@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_G(Icons.image_outlined,'Images: JPG, PNG, WEBP'),_G(Icons.picture_as_pdf_outlined,'Documents: PDF'),_G(Icons.music_note_outlined,'Audio: MP3, WAV'),_G(Icons.movie_outlined,'Video: MP4, MOV'),SizedBox(height:8),Text('Maximum dummy file size: 10 MB',style:TextStyle(color:AppConstants.textSecondary,fontSize:10))]);}
class _G extends StatelessWidget{final IconData i;final String t;const _G(this.i,this.t);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Row(children:[Icon(i,size:18,color:AppConstants.primaryRed),const SizedBox(width:10),Text(t,style:const TextStyle(fontSize:12))]));}
