import 'package:flutter/material.dart';
import '../../../core/constants/app_constants.dart';
import '../../widgets/forms/admin_form_section.dart';
import 'widgets/announcement_message_section.dart';
import 'widgets/announcement_target_section.dart';
class CreateAnnouncementPage extends StatefulWidget{const CreateAnnouncementPage({super.key});@override State<CreateAnnouncementPage> createState()=>_CreateAnnouncementPageState();}
class _CreateAnnouncementPageState extends State<CreateAnnouncementPage>{String priority='Normal',status='Active';bool scheduled=false;void publish()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Announcement published as dummy data.')));
@override Widget build(BuildContext c)=>Scaffold(
  backgroundColor:AppConstants.pageBackground,appBar:AppBar(title:const Text('Create Announcement'),leading:IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded))),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1150),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const _Intro(),const SizedBox(height:16),LayoutBuilder(builder:(c,cs)=>_layout(cs.maxWidth>=900)),const SizedBox(height:18),Align(alignment:Alignment.centerRight,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppConstants.primaryRed),onPressed:publish,icon:const Icon(Icons.campaign_outlined),label:const Text('Publish Announcement')))])))));
Widget _layout(bool wide){final main=const AdminFormSection(title:'Announcement Details',child:Column(children:[AdminTextField(label:'Title',hint:'Enter announcement title'),SizedBox(height:14),AnnouncementMessageSection()]));final side=Column(children:[AdminFormSection(title:'Publishing',child:Column(children:[AdminDropdown(label:'Priority',value:priority,items:const['Normal','Important','Urgent'],onChanged:(v){if(v!=null)setState(()=>priority=v);}),const SizedBox(height:14),AdminDropdown(label:'Status',value:status,items:const['Active','Draft','Expired'],onChanged:(v){if(v!=null)setState(()=>status=v);}),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Schedule announcement',style:TextStyle(fontSize:12)),value:scheduled,activeThumbColor:AppConstants.primaryRed,onChanged:(v)=>setState(()=>scheduled=v)),if(scheduled)const AdminTextField(label:'Publish Date',hint:'Jun 25, 2025',suffixIcon:Icon(Icons.calendar_today_outlined))])),const SizedBox(height:16),const AnnouncementTargetSection()]);return wide?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:7,child:main),const SizedBox(width:16),Expanded(flex:3,child:side)]):Column(children:[main,const SizedBox(height:16),side]);}
}
class _Intro extends StatelessWidget{const _Intro();@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Create Announcement',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Share important updates with your audience.',style:TextStyle(color:AppConstants.textSecondary,fontSize:12))]);}
