// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYja__Sj1kDrfel9A2YUzCkuEw9M14vwQ',
    appId: '1:1042537177373:web:bc460a5238d062167b01f4',
    messagingSenderId: '1042537177373',
    projectId: 'chaturvyuha-foundation-afcde',
    authDomain: 'chaturvyuha-foundation-afcde.firebaseapp.com',
    storageBucket: 'chaturvyuha-foundation-afcde.firebasestorage.app',
    measurementId: 'G-DK5QY56ZLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnai5XA8byC1en6Eo00N_N5LeuaZPTOg',
    appId: '1:1042537177373:android:1ad9be3602af3a0c7b01f4',
    messagingSenderId: '1042537177373',
    projectId: 'chaturvyuha-foundation-afcde',
    storageBucket: 'chaturvyuha-foundation-afcde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8GRoX9mJkoAW4x4b0H-sRPF83SqfBWo',
    appId: '1:1042537177373:ios:d8038f2ce12f0aac7b01f4',
    messagingSenderId: '1042537177373',
    projectId: 'chaturvyuha-foundation-afcde',
    storageBucket: 'chaturvyuha-foundation-afcde.firebasestorage.app',
    iosBundleId: 'com.example.chaturvyuhaFoundation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ8GRoX9mJkoAW4x4b0H-sRPF83SqfBWo',
    appId: '1:1042537177373:ios:d8038f2ce12f0aac7b01f4',
    messagingSenderId: '1042537177373',
    projectId: 'chaturvyuha-foundation-afcde',
    storageBucket: 'chaturvyuha-foundation-afcde.firebasestorage.app',
    iosBundleId: 'com.example.chaturvyuhaFoundation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYja__Sj1kDrfel9A2YUzCkuEw9M14vwQ',
    appId: '1:1042537177373:web:47adcb9c61e680957b01f4',
    messagingSenderId: '1042537177373',
    projectId: 'chaturvyuha-foundation-afcde',
    authDomain: 'chaturvyuha-foundation-afcde.firebaseapp.com',
    storageBucket: 'chaturvyuha-foundation-afcde.firebasestorage.app',
    measurementId: 'G-T13PS0H6B3',
  );
}
