import 'package:flutter/material.dart';
import '../../../core/constants/app_constants.dart';
import '../../widgets/forms/admin_form_section.dart';
import '../../widgets/forms/image_upload_box.dart';
import 'widgets/article_editor_section.dart';
import 'widgets/article_seo_section.dart';

class CreateArticlePage extends StatefulWidget { const CreateArticlePage({super.key}); @override State<CreateArticlePage> createState()=>_CreateArticlePageState(); }
class _CreateArticlePageState extends State<CreateArticlePage>{ String category='Culture',author='Sitaram Rokka',status='Draft'; bool featured=true;
 void save()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Article saved as dummy data.')));
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppConstants.pageBackground,appBar:AppBar(title:const Text('Create Article'),leading:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded))),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1250),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const _Intro(),const SizedBox(height:16),LayoutBuilder(builder:(context,c)=>_layout(c.maxWidth>=900)),const SizedBox(height:18),Align(alignment:Alignment.centerRight,child:Wrap(spacing:10,children:[OutlinedButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Preview opened.'))),child:const Text('Preview')),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppConstants.primaryRed),onPressed:save,icon:const Icon(Icons.save_outlined),label:Text(status=='Published'?'Publish Article':'Save Article'))]))])))));
 Widget _layout(bool wide){final main=Column(children:[const AdminFormSection(title:'Basic Information',subtitle:'Add the main details of your article.',child:Column(children:[AdminTextField(label:'Title',hint:'Enter article title'),SizedBox(height:14),AdminTextField(label:'Slug',hint:'article-url-slug')])),const SizedBox(height:16),const ArticleEditorSection(),const SizedBox(height:16),const ArticleSeoSection()]); final side=Column(children:[AdminFormSection(title:'Publishing',child:Column(children:[AdminDropdown(label:'Category',value:category,items:const['Culture','Education','Yoga','Spiritual','Health'],onChanged:(v){if(v!=null)setState(()=>category=v);}),const SizedBox(height:14),AdminDropdown(label:'Author',value:author,items:const['Sitaram Rokka','Ram Sharma','Hari Thapa'],onChanged:(v){if(v!=null)setState(()=>author=v);}),const SizedBox(height:14),AdminDropdown(label:'Status',value:status,items:const['Draft','Published','Scheduled'],onChanged:(v){if(v!=null)setState(()=>status=v);}),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Featured article',style:TextStyle(fontSize:12)),value:featured,activeThumbColor:AppConstants.primaryRed,onChanged:(v)=>setState(()=>featured=v))])),const SizedBox(height:16),const AdminFormSection(title:'Featured Image',child:ImageUploadBox(height:190,subtitle:'Recommended 1200 × 700 px'))]); return wide?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:7,child:main),const SizedBox(width:16),Expanded(flex:3,child:side)]):Column(children:[main,const SizedBox(height:16),side]);}
}
class _Intro extends StatelessWidget{const _Intro();@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Create Article',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Write and publish meaningful content.',style:TextStyle(color:AppConstants.textSecondary,fontSize:12))]);}
