import 'package:flutter/material.dart';
import '../../../core/constants/app_constants.dart';
import '../../widgets/forms/admin_form_section.dart';
import '../../widgets/forms/image_upload_box.dart';
import 'widgets/event_location_section.dart';
import 'widgets/event_registration_section.dart';
class CreateEventPage extends StatefulWidget{const CreateEventPage({super.key});@override State<CreateEventPage> createState()=>_CreateEventPageState();}
class _CreateEventPageState extends State<CreateEventPage>{String category='Culture',status='Published';bool registration=true;void save()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Event saved as dummy data.')));
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:AppConstants.pageBackground,appBar:AppBar(title:const Text('Create Event'),leading:IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded))),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1200),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const _Intro(),const SizedBox(height:16),LayoutBuilder(builder:(c,cs)=>_layout(cs.maxWidth>=900)),const SizedBox(height:18),Align(alignment:Alignment.centerRight,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppConstants.primaryRed),onPressed:save,icon:const Icon(Icons.publish_outlined),label:const Text('Publish Event')))])))));
Widget _layout(bool wide){final main=Column(children:[const AdminFormSection(title:'Event Details',child:Column(children:[AdminTextField(label:'Event Name',hint:'Enter event name'),SizedBox(height:14),AdminTextField(label:'Description',hint:'Describe your event',maxLines:5)])),const SizedBox(height:16),const EventLocationSection(),const SizedBox(height:16),EventRegistrationSection(enabled:registration,onChanged:(v)=>setState(()=>registration=v))]);final side=Column(children:[AdminFormSection(title:'Event Settings',child:Column(children:[AdminDropdown(label:'Category',value:category,items:const['Culture','Education','Yoga','Youth','Spiritual'],onChanged:(v){if(v!=null)setState(()=>category=v);}),const SizedBox(height:14),AdminDropdown(label:'Status',value:status,items:const['Published','Draft','Upcoming'],onChanged:(v){if(v!=null)setState(()=>status=v);})])),const SizedBox(height:16),const AdminFormSection(title:'Featured Image',child:ImageUploadBox(height:190,subtitle:'Recommended 1200 × 700 px'))]);return wide?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:7,child:main),const SizedBox(width:16),Expanded(flex:3,child:side)]):Column(children:[main,const SizedBox(height:16),side]);}
}
class _Intro extends StatelessWidget{const _Intro();@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Create Event',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Manage an event, its location, schedule and registration.',style:TextStyle(color:AppConstants.textSecondary,fontSize:12))]);}
